import turtle
wn = turtle.Screen()
colin = turtle.Turtle()
colin.shape("turtle")

colin.color("purple")

colin.forward(50)
colin.left(90)
colin.forward(50)
colin.left(90)
colin.forward(50)
colin.left(90)
colin.forward(50)
colin.penup()
colin.color("red")
colin.forward(10)
colin.pendown()
colin.forward(50)
colin.left(90)
colin.forward(50)
colin.left(90)
colin.forward(50)
colin.left(90)
colin.forward(50)
wn.exitonclick()
